/*
 * Book API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.UUID;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * BookResponse
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T18:13:04.746056155Z[GMT]")

public class BookResponse {
  @SerializedName("id")
  private String id = null;

  @SerializedName("nazwa")
  private String nazwa = null;

  @SerializedName("gatunek")
  private String gatunek = null;

  @SerializedName("cena")
  private Float cena = null;

  @SerializedName("iloscStron")
  private Integer iloscStron = null;

  @SerializedName("licznikOdwiedzin")
  private Integer licznikOdwiedzin = null;

  @SerializedName("sztuki")
  private Integer sztuki = null;

  @SerializedName("authorId")
  private String authorId = null;

  @SerializedName("authorName")
  private String authorName = null;

  public BookResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public BookResponse nazwa(String nazwa) {
    this.nazwa = nazwa;
    return this;
  }

   /**
   * Get nazwa
   * @return nazwa
  **/
  @Schema(required = true, description = "")
  public String getNazwa() {
    return nazwa;
  }

  public void setNazwa(String nazwa) {
    this.nazwa = nazwa;
  }

  public BookResponse gatunek(String gatunek) {
    this.gatunek = gatunek;
    return this;
  }

   /**
   * Get gatunek
   * @return gatunek
  **/
  @Schema(required = true, description = "")
  public String getGatunek() {
    return gatunek;
  }

  public void setGatunek(String gatunek) {
    this.gatunek = gatunek;
  }

  public BookResponse cena(Float cena) {
    this.cena = cena;
    return this;
  }

   /**
   * Get cena
   * @return cena
  **/
  @Schema(required = true, description = "")
  public Float getCena() {
    return cena;
  }

  public void setCena(Float cena) {
    this.cena = cena;
  }

  public BookResponse iloscStron(Integer iloscStron) {
    this.iloscStron = iloscStron;
    return this;
  }

   /**
   * Get iloscStron
   * @return iloscStron
  **/
  @Schema(required = true, description = "")
  public Integer getIloscStron() {
    return iloscStron;
  }

  public void setIloscStron(Integer iloscStron) {
    this.iloscStron = iloscStron;
  }

  public BookResponse licznikOdwiedzin(Integer licznikOdwiedzin) {
    this.licznikOdwiedzin = licznikOdwiedzin;
    return this;
  }

   /**
   * Get licznikOdwiedzin
   * @return licznikOdwiedzin
  **/
  @Schema(required = true, description = "")
  public Integer getLicznikOdwiedzin() {
    return licznikOdwiedzin;
  }

  public void setLicznikOdwiedzin(Integer licznikOdwiedzin) {
    this.licznikOdwiedzin = licznikOdwiedzin;
  }

  public BookResponse sztuki(Integer sztuki) {
    this.sztuki = sztuki;
    return this;
  }

   /**
   * Get sztuki
   * @return sztuki
  **/
  @Schema(required = true, description = "")
  public Integer getSztuki() {
    return sztuki;
  }

  public void setSztuki(Integer sztuki) {
    this.sztuki = sztuki;
  }

  public BookResponse authorId(String authorId) {
    this.authorId = authorId;
    return this;
  }

   /**
    * Get authorId
    *
    * @return authorId
    **/
  @Schema(required = true, description = "")
  public UUID getAuthorId() {
    return UUID.fromString(authorId);
  }

  public void setAuthorId(String authorId) {
    this.authorId = authorId;
  }

  public BookResponse authorName(String authorName) {
    this.authorName = authorName;
    return this;
  }

   /**
   * Get authorName
   * @return authorName
  **/
  @Schema(required = true, description = "")
  public String getAuthorName() {
    return authorName;
  }

  public void setAuthorName(String authorName) {
    this.authorName = authorName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookResponse bookResponse = (BookResponse) o;
    return Objects.equals(this.id, bookResponse.id) &&
        Objects.equals(this.nazwa, bookResponse.nazwa) &&
        Objects.equals(this.gatunek, bookResponse.gatunek) &&
        Objects.equals(this.cena, bookResponse.cena) &&
        Objects.equals(this.iloscStron, bookResponse.iloscStron) &&
        Objects.equals(this.licznikOdwiedzin, bookResponse.licznikOdwiedzin) &&
        Objects.equals(this.sztuki, bookResponse.sztuki) &&
        Objects.equals(this.authorId, bookResponse.authorId) &&
        Objects.equals(this.authorName, bookResponse.authorName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nazwa, gatunek, cena, iloscStron, licznikOdwiedzin, sztuki, authorId, authorName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nazwa: ").append(toIndentedString(nazwa)).append("\n");
    sb.append("    gatunek: ").append(toIndentedString(gatunek)).append("\n");
    sb.append("    cena: ").append(toIndentedString(cena)).append("\n");
    sb.append("    iloscStron: ").append(toIndentedString(iloscStron)).append("\n");
    sb.append("    licznikOdwiedzin: ").append(toIndentedString(licznikOdwiedzin)).append("\n");
    sb.append("    sztuki: ").append(toIndentedString(sztuki)).append("\n");
    sb.append("    authorId: ").append(toIndentedString(authorId)).append("\n");
    sb.append("    authorName: ").append(toIndentedString(authorName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
