/*
 * Book API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BookRequest
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T18:13:04.746056155Z[GMT]")

public class BookRequest {
  @SerializedName("nazwa")
  private String nazwa = null;

  @SerializedName("gatunek")
  private String gatunek = null;

  @SerializedName("cena")
  private Float cena = null;

  @SerializedName("iloscStron")
  private Integer iloscStron = null;

  @SerializedName("licznikOdwiedzin")
  private Integer licznikOdwiedzin = null;

  @SerializedName("sztuki")
  private Integer sztuki = null;

  @SerializedName("authorId")
  private String authorId = null;

  public BookRequest nazwa(String nazwa) {
    this.nazwa = nazwa;
    return this;
  }

   /**
   * Get nazwa
   * @return nazwa
  **/
  @Schema(required = true, description = "")
  public String getNazwa() {
    return nazwa;
  }

  public void setNazwa(String nazwa) {
    this.nazwa = nazwa;
  }

  public BookRequest gatunek(String gatunek) {
    this.gatunek = gatunek;
    return this;
  }

   /**
   * Get gatunek
   * @return gatunek
  **/
  @Schema(required = true, description = "")
  public String getGatunek() {
    return gatunek;
  }

  public void setGatunek(String gatunek) {
    this.gatunek = gatunek;
  }

  public BookRequest cena(Float cena) {
    this.cena = cena;
    return this;
  }

   /**
   * Get cena
   * @return cena
  **/
  @Schema(required = true, description = "")
  public Float getCena() {
    return cena;
  }

  public void setCena(Float cena) {
    this.cena = cena;
  }

  public BookRequest iloscStron(Integer iloscStron) {
    this.iloscStron = iloscStron;
    return this;
  }

   /**
   * Get iloscStron
   * @return iloscStron
  **/
  @Schema(required = true, description = "")
  public Integer getIloscStron() {
    return iloscStron;
  }

  public void setIloscStron(Integer iloscStron) {
    this.iloscStron = iloscStron;
  }

  public BookRequest licznikOdwiedzin(Integer licznikOdwiedzin) {
    this.licznikOdwiedzin = licznikOdwiedzin;
    return this;
  }

   /**
   * Get licznikOdwiedzin
   * @return licznikOdwiedzin
  **/
  @Schema(required = true, description = "")
  public Integer getLicznikOdwiedzin() {
    return licznikOdwiedzin;
  }

  public void setLicznikOdwiedzin(Integer licznikOdwiedzin) {
    this.licznikOdwiedzin = licznikOdwiedzin;
  }

  public BookRequest sztuki(Integer sztuki) {
    this.sztuki = sztuki;
    return this;
  }

   /**
   * Get sztuki
   * @return sztuki
  **/
  @Schema(required = true, description = "")
  public Integer getSztuki() {
    return sztuki;
  }

  public void setSztuki(Integer sztuki) {
    this.sztuki = sztuki;
  }

  public BookRequest authorId(String authorId) {
    this.authorId = authorId;
    return this;
  }

   /**
   * Get authorId
   * @return authorId
  **/
  @Schema(required = true, description = "")
  public String getAuthorId() {
    return authorId;
  }

  public void setAuthorId(String authorId) {
    this.authorId = authorId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookRequest bookRequest = (BookRequest) o;
    return Objects.equals(this.nazwa, bookRequest.nazwa) &&
        Objects.equals(this.gatunek, bookRequest.gatunek) &&
        Objects.equals(this.cena, bookRequest.cena) &&
        Objects.equals(this.iloscStron, bookRequest.iloscStron) &&
        Objects.equals(this.licznikOdwiedzin, bookRequest.licznikOdwiedzin) &&
        Objects.equals(this.sztuki, bookRequest.sztuki) &&
        Objects.equals(this.authorId, bookRequest.authorId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nazwa, gatunek, cena, iloscStron, licznikOdwiedzin, sztuki, authorId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookRequest {\n");
    
    sb.append("    nazwa: ").append(toIndentedString(nazwa)).append("\n");
    sb.append("    gatunek: ").append(toIndentedString(gatunek)).append("\n");
    sb.append("    cena: ").append(toIndentedString(cena)).append("\n");
    sb.append("    iloscStron: ").append(toIndentedString(iloscStron)).append("\n");
    sb.append("    licznikOdwiedzin: ").append(toIndentedString(licznikOdwiedzin)).append("\n");
    sb.append("    sztuki: ").append(toIndentedString(sztuki)).append("\n");
    sb.append("    authorId: ").append(toIndentedString(authorId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
